### ISSUE TITLE
Kindle paperwhite 2024, FW 5.17.0 failed to open in calibre

### ISSUE THREAD

**Issue by strobes1** [libmtp/libmtp#231]
Ubuntu 22.04, calibre 7.6.0+ds-1build1
I can see the Kindle mounted, and can navigate folders, transfer files.

$ calibre
Device 0 (VID=1949 and PID=9981) is UNKNOWN in libmtp v1.1.21.
Please report this VID/PID and the device model to the libmtp development team
libusb_claim_interface() reports device is busy, likely in use by GVFS or KDE MTP device handling alreadyLIBMTP PANIC: Unable to initialize device
Error while trying to open MTPDevice(busnum=1, devnum=7, vendor_id=6473, product_id=39297, bcd=547, serial='GN433X0742870C8S', manufacturer='Amazon', product='Kindle Paperwhite') (Driver: <calibre.devices.mtp.driver.MTP_DEVICE object at 0x79adb4763b90>)
Traceback (most recent call last):
  File "calibre/devices/mtp/unix/driver.py", line 218, in open
  File "calibre/devices/mtp/base.py", line 24, in synchronizer
  File "calibre/devices/mtp/unix/driver.py", line 170, in create_device
libmtp.MTPError: Unable to open MTP device with busnum=1 and devnum=7, tried 1 such devices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 351, in detect_device
  File "calibre/devices/mtp/driver.py", line 148, in open
  File "calibre/devices/mtp/base.py", line 24, in synchronizer
  File "calibre/devices/mtp/unix/driver.py", line 221, in open
calibre.devices.errors.OpenFailed: Failed to open MTPDevice(busnum=1, devnum=7, vendor_id=6473, product_id=39297, bcd=547, serial='xxxxxxxxxxxxxxxxxxx', manufacturer='Amazon', product='Kindle Paperwhite'): Error: Unable to open MTP device with busnum=1 and devnum=7, tried 1 such devices

**Comment by msmeissn** [comment]
libusb_claim_interface() reports device is busy, 

you might need to umount it from nautilus.

**Comment by olegk25** [comment]
Hello, a similar issue here:

ArchLinux  6.12.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000 x86_64 GNU/Linux

```
calibre 7.22  embedded-python: False
Linux-6.12.6-arch1-1-x86_64-with-glibc2.40 Linux ('64bit', 'ELF')
('Linux', '6.12.6-arch1-1', '#1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000')
Python 3.13.1
Interface language: None
EXE path: /usr/bin/python3
USB devices on system:
[['0x62a', '0x7269', '0x207', 'Full-Speed Mouse', 'Full-Speed Mouse', ''],
 ['0x4f2',
  '0xb52c',
  '0x29',
  'Chicony Electronics Co.,Ltd.',
  'Integrated Camera',
  '0001'],
 ['0x8087', '0xa2b', '0x1', '', '', ''],
 ['0x1949',
  '0x9981',
  '0x223',
  'Amazon',
  'Kindle Paperwhite',
  'masked']]

No disabled plugins
Looking for devices of type: MTP_DEVICE
MTP devices connected:
USBDevice(busnum=1, devnum=13, vendor_id=0x1949, product_id=0x9981, bcd=0x0223, manufacturer=Amazon, product=Kindle Paperwhite, serial=[masked])

Trying to open: USBDevice(busnum=1, devnum=13, vendor_id=0x1949, product_id=0x9981, bcd=0x0223, manufacturer=Amazon, product=Kindle Paperwhite, serial=[masked])
Opening device failed:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/mtp/unix/driver.py", line 218, in open
    self.dev = self.create_device(connected_device)
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/devices/mtp/base.py", line 24, in synchronizer
    return func(self, *args, **kwargs)
  File "/usr/lib/calibre/calibre/devices/mtp/unix/driver.py", line 170, in create_device
    return self.libmtp.Device(d.busnum, d.devnum, d.vendor_id,
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            d.product_id, man, prod, d.serial)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libmtp.MTPError: Unable to open MTP device with busnum=1 and devnum=13, tried 1 such devices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/mtp/unix/driver.py", line 148, in debug_managed_device_detection
    self.open(d, 'debug')
    ~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/devices/mtp/driver.py", line 148, in open
    BASE.open(self, device, library_uuid)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/devices/mtp/base.py", line 24, in synchronizer
    return func(self, *args, **kwargs)
  File "/usr/lib/calibre/calibre/devices/mtp/unix/driver.py", line 221, in open
    raise OpenFailed('Failed to open %s: Error: %s'%(
            connected_device, as_unicode(e)))
calibre.devices.errors.OpenFailed: Failed to open USBDevice(busnum=1, devnum=13, vendor_id=0x1949, product_id=0x9981, bcd=0x0223, manufacturer=Amazon, product=Kindle Paperwhite, serial=[masked]): Error: Unable to open MTP device with busnum=1 and devnum=13, tried 1 such devices

```

**Comment by olegk25** [comment]
Hello, I've posted a similar comment, but apparently it's something inherent to the MTP protocol - it can only support single connection. In the case with Calibre - the file managed is auto-mounting it.. If you disable the auto-mount, Calibre will see it.

**Comment by ludrol** [comment]
I have same problem when trying to mount kindle 11 (2022) via jmtpfs

**Comment by yananet** [comment]
To disable MTP auto-mounting,
see if it is enabled
```
systemctl --user status gvfs-mtp-volume-monitor.service
```

Stop it
```
systemctl --user stop gvfs-mtp-volume-monitor.service
```

or disable it
```
systemctl --user disable --now gvfs-mtp-volume-monitor.service
```
then I could now read it from Calibre.
