### ISSUE TITLE
Oculus vr headset not recogised

### ISSUE THREAD

**Issue by marcinkubica** [libmtp/libmtp#27]
Hi
```
libmtp version: 1.1.16

Listing raw device(s)
Device 0 (VID=2833 and PID=0082) is UNKNOWN in libmtp v1.1.16.
Please report this VID/PID and the device model to the libmtp development team
   Found 1 device(s):
   2833:0082 @ bus 1, dev 15
Attempting to connect device(s)
error returned by libusb_claim_interface() = -6LIBMTP PANIC: Unable to initialize device
Unable to open raw device 0
OK.

```

**Comment by msmeissn** [comment]
does it work when run as root?

**Comment by gwillen** [comment]
Note that they seem to be revving the PID with reckless abandon; my Oculus Quest shows up as VID=2833, PID=0183. (It seems to show up under a different PID depending on whether I connect it directly to the macbookpro, or via a C-to-A cable and an A-to-C adapter (ADB does not work in this configuration.)

**Comment by gwillen** [comment]
Also, I get the same issue described above when running as root:

```
(venv) bunneh:Downloads root# python3
Python 3.7.6 (default, Dec 30 2019, 19:38:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymtp
>>> mtp=pymtp.MTP()
>>> mtp.connect()
Device 0 (VID=2833 and PID=0183) is UNKNOWN in libmtp v1.1.17.
Please report this VID/PID and the device model to the libmtp development team
error returned by libusb_claim_interface() = -3LIBMTP PANIC: Unable to initialize device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gwillen/Downloads/venv/lib/python3.7/site-packages/pymtp.py", line 515, in connect
    raise NoDeviceConnected
pymtp.NoDeviceConnected
>>> 
```

Not sure why running as root would affect the presence of the device on the whitelist.
